### ISSUE TITLE
Why is unknown traces of table creation seen in the logs

### ISSUE THREAD

**Issue by rajeshkp** [indirect/rails-footnotes#94] opened 2013-08-17 19:10 UTC
Why is unknown traces of table creation seen in the logs, how do I prevent this.

UNKNOWN (trace)
SHOW CREATE TABLE foo
SCHEMA (0.002ms)  
UNKNOWN (trace)
SHOW FULL FIELDS FROM foo
SCHEMA (0.003ms)

**Comment by indirect** [comment] 2023-11-30 00:18
Happy to reopen and investigate if you can provide reproduction steps, but closing for now since I am not able to reproduce this.

**Closed by indirect** 2023-11-30 00:18 UTC
Labels: Feedback
